import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const sampleBooks = [
  // ========== BUKU INDONESIA POPULER 2020-2025 (50 buku) ==========
  {
    title: "Laut Bercerita",
    author: "Leila S. Chudori",
    genre: "Fiksi Sejarah",
    rating: 4.8,
    vibes: ["mengharukan", "historis", "emosional"],
    themes: ["kemanusiaan", "perjuangan", "kehilangan"],
    pages: 379,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Hujan",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.7,
    vibes: ["magis", "petualangan", "misterius"],
    themes: ["persahabatan", "keluarga", "supernatural"],
    pages: 320,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Gadis Kretek",
    author: "Ratih Kumala",
    genre: "Roman",
    rating: 4.6,
    vibes: ["romantis", "nostalgia", "indah"],
    themes: ["cinta", "sejarah", "budaya"],
    pages: 370,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Ronggeng Dukuh Paruk",
    author: "Ahmad Tohari",
    genre: "Fiksi Sastra",
    rating: 4.9,
    vibes: ["filosofis", "tradisional", "mendalam"],
    themes: ["tradisi", "konflik", "identitas"],
    pages: 198,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Pulang",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.7,
    vibes: ["mengharukan", "inspiratif", "penuh makna"],
    themes: ["keluarga", "penebusan", "harapan"],
    pages: 400,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Bumi Manusia",
    author: "Pramoedya Ananta Toer",
    genre: "Fiksi Sejarah",
    rating: 4.8,
    vibes: ["epik", "revolusioner", "kuat"],
    themes: ["kolonialisme", "pendidikan", "keadilan"],
    pages: 535,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Cantik Itu Luka",
    author: "Eka Kurniawan",
    genre: "Realisme Magis",
    rating: 4.7,
    vibes: ["dark", "surreal", "kompleks"],
    themes: ["sejarah", "keluarga", "supernatural"],
    pages: 520,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Pergi",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.6,
    vibes: ["petualangan", "inspiratif", "mengharukan"],
    themes: ["perjalanan", "kehidupan", "makna"],
    pages: 380,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Tentang Kamu",
    author: "Tere Liye",
    genre: "Roman",
    rating: 4.5,
    vibes: ["romantis", "ringan", "menyentuh"],
    themes: ["cinta", "kehidupan", "takdir"],
    pages: 350,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Negeri 5 Menara",
    author: "Ahmad Fuadi",
    genre: "Fiksi Inspiratif",
    rating: 4.7,
    vibes: ["inspiratif", "penuh semangat", "mengharukan"],
    themes: ["pendidikan", "persahabatan", "mimpi"],
    pages: 423,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Perempuan Yang Menangis Kepada Bulan Hitam",
    author: "Dian Purnomo",
    genre: "Puisi",
    rating: 4.5,
    vibes: ["melankolik", "puitis", "introspektif"],
    themes: ["cinta", "kehilangan", "eksistensial"],
    pages: 180,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Seperti Dendam, Rindu Harus Dibayar Tuntas",
    author: "Eka Kurniawan",
    genre: "Thriller",
    rating: 4.6,
    vibes: ["intense", "dark", "menegangkan"],
    themes: ["balas dendam", "kekerasan", "obsesi"],
    pages: 198,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Bumi",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.8,
    vibes: ["magis", "seru", "penuh teka-teki"],
    themes: ["persahabatan", "kekuatan", "paralel"],
    pages: 440,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Bulan",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.7,
    vibes: ["misteri", "magis", "menegangkan"],
    themes: ["petualangan", "kegelapan", "harapan"],
    pages: 400,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Matahari",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.8,
    vibes: ["epik", "heroik", "emosional"],
    themes: ["pengorbanan", "keberanian", "cinta"],
    pages: 420,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Si Anak Badai",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.7,
    vibes: ["petualangan", "magis", "seru"],
    themes: ["persahabatan", "keberanian", "supernatural"],
    pages: 400,
    year: 2022,
    language: "Indonesian",
  },
  {
    title: "Orang-Orang Biasa",
    author: "Andrea Hirata",
    genre: "Fiksi",
    rating: 4.6,
    vibes: ["inspiratif", "hangat", "optimis"],
    themes: ["kehidupan", "perjuangan", "harapan"],
    pages: 350,
    year: 2022,
    language: "Indonesian",
  },
  {
    title: "Laskar Pelangi",
    author: "Andrea Hirata",
    genre: "Fiksi Inspiratif",
    rating: 4.8,
    vibes: ["inspiratif", "mengharukan", "ceria"],
    themes: ["pendidikan", "kemiskinan", "mimpi"],
    pages: 529,
    year: 2022,
    language: "Indonesian",
  },
  {
    title: "Sang Pemimpi",
    author: "Andrea Hirata",
    genre: "Fiksi Inspiratif",
    rating: 4.7,
    vibes: ["penuh semangat", "optimis", "menyentuh"],
    themes: ["mimpi", "persahabatan", "perjuangan"],
    pages: 292,
    year: 2022,
    language: "Indonesian",
  },
  {
    title: "Edensor",
    author: "Andrea Hirata",
    genre: "Fiksi Inspiratif",
    rating: 4.6,
    vibes: ["petualangan", "inspiratif", "romantis"],
    themes: ["cinta", "perjalanan", "impian"],
    pages: 300,
    year: 2022,
    language: "Indonesian",
  },
  {
    title: "Rindu",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.6,
    vibes: ["emosional", "mendalam", "menyentuh"],
    themes: ["kerinduan", "kehilangan", "cinta"],
    pages: 370,
    year: 2022,
    language: "Indonesian",
  },
  {
    title: "Komet",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.5,
    vibes: ["misterius", "seru", "penuh aksi"],
    themes: ["misteri", "petualangan", "persahabatan"],
    pages: 390,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Komet Minor",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.6,
    vibes: ["menegangkan", "penuh teka-teki", "magis"],
    themes: ["petualangan", "bahaya", "kesetiaan"],
    pages: 410,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Funiculi Funicula",
    author: "Toshikazu Kawaguchi (Terjemahan)",
    genre: "Fiksi Fantasi",
    rating: 4.5,
    vibes: ["filosofis", "menyentuh", "magis"],
    themes: ["waktu", "penyesalan", "hubungan"],
    pages: 213,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Selamat Tinggal",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.6,
    vibes: ["emosional", "mendalam", "reflektif"],
    themes: ["perpisahan", "kehilangan", "makna hidup"],
    pages: 380,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Nebula",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.7,
    vibes: ["epik", "dramatis", "menegangkan"],
    themes: ["konflik", "keberanian", "pengorbanan"],
    pages: 450,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Selena",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.6,
    vibes: ["emosional", "heroik", "menyentuh"],
    themes: ["keluarga", "pengorbanan", "cinta"],
    pages: 430,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Lumpu",
    author: "Tere Liye",
    genre: "Fiksi Petualangan",
    rating: 4.5,
    vibes: ["misterius", "gelap", "intens"],
    themes: ["misteri", "kegelapan", "perjuangan"],
    pages: 400,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Luka Tanah",
    author: "Leila S. Chudori",
    genre: "Fiksi Sejarah",
    rating: 4.7,
    vibes: ["powerful", "historis", "kompleks"],
    themes: ["sejarah", "trauma", "identitas"],
    pages: 420,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Matahari Minor",
    author: "Gita Savitri Devi",
    genre: "Nonfiksi",
    rating: 4.5,
    vibes: ["inspiratif", "pribadi", "jujur"],
    themes: ["kehidupan", "refleksi", "pertumbuhan"],
    pages: 250,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Rectoverso",
    author: "Dee Lestari",
    genre: "Kumpulan Cerpen",
    rating: 4.6,
    vibes: ["romantis", "filosofis", "beragam"],
    themes: ["cinta", "hubungan", "kehidupan"],
    pages: 306,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Perahu Kertas",
    author: "Dee Lestari",
    genre: "Roman",
    rating: 4.7,
    vibes: ["romantis", "inspiratif", "menyentuh"],
    themes: ["cinta", "mimpi", "seni"],
    pages: 444,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Supernova: Kesatria, Putri, dan Bintang Jatuh",
    author: "Dee Lestari",
    genre: "Fiksi Filosofis",
    rating: 4.5,
    vibes: ["filosofis", "kompleks", "romantis"],
    themes: ["eksistensial", "cinta", "sains"],
    pages: 326,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Negeri Para Bedebah",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.5,
    vibes: ["gelap", "realistis", "keras"],
    themes: ["korupsi", "keadilan", "perlawanan"],
    pages: 450,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Daun Yang Jatuh Tak Pernah Membenci Angin",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.8,
    vibes: ["mengharukan", "inspiratif", "emosional"],
    themes: ["keluarga", "perjuangan", "ikhlas"],
    pages: 320,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Hafalan Shalat Delisa",
    author: "Tere Liye",
    genre: "Fiksi",
    rating: 4.7,
    vibes: ["mengharukan", "inspiratif", "spiritual"],
    themes: ["bencana", "ketabahan", "iman"],
    pages: 330,
    year: 2024,
    language: "Indonesian",
  },
  {
    title: "Ayah",
    author: "Andrea Hirata",
    genre: "Fiksi",
    rating: 4.6,
    vibes: ["mengharukan", "filosofis", "mendalam"],
    themes: ["keluarga", "cinta", "kehidupan"],
    pages: 280,
    year: 2025,
    language: "Indonesian",
  },
  {
    title: "Cinta di Dalam Gelas",
    author: "Andrea Hirata",
    genre: "Roman",
    rating: 4.4,
    vibes: ["romantis", "lucu", "ringan"],
    themes: ["cinta", "komedi", "kehidupan"],
    pages: 310,
    year: 2025,
    language: "Indonesian",
  },
  {
    title: "Padang Bulan",
    author: "Andrea Hirata",
    genre: "Fiksi",
    rating: 4.5,
    vibes: ["misterius", "romantis", "nostalgia"],
    themes: ["cinta", "misteri", "budaya"],
    pages: 400,
    year: 2025,
    language: "Indonesian",
  },
  {
    title: "Sabtu Bersama Bapak",
    author: "Adhitya Mulya",
    genre: "Fiksi",
    rating: 4.6,
    vibes: ["mengharukan", "hangat", "keluarga"],
    themes: ["ayah", "keluarga", "waktu"],
    pages: 280,
    year: 2025,
    language: "Indonesian",
  },
  {
    title: "Critical Eleven",
    author: "Ika Natassa",
    genre: "Roman",
    rating: 4.5,
    vibes: ["romantis", "realistis", "emosional"],
    themes: ["cinta", "pilihan", "takdir"],
    pages: 344,
    year: 2025,
    language: "Indonesian",
  },
  {
    title: "A Very Yuppy Wedding",
    author: "Ika Natassa",
    genre: "Roman",
    rating: 4.3,
    vibes: ["ringan", "romantis", "menghibur"],
    themes: ["pernikahan", "cinta", "keluarga"],
    pages: 320,
    year: 2025,
    language: "Indonesian",
  },
  {
    title: "Divortiare",
    author: "Ika Natassa",
    genre: "Roman",
    rating: 4.4,
    vibes: ["realistis", "emosional", "dewasa"],
    themes: ["pernikahan", "perceraian", "kehidupan"],
    pages: 368,
    year: 2025,
    language: "Indonesian",
  },
  {
    title: "Dilan 1990",
    author: "Pidi Baiq",
    genre: "Roman",
    rating: 4.7,
    vibes: ["romantis", "nostalgia", "manis"],
    themes: ["cinta remaja", "kenangan", "romantis"],
    pages: 332,
    year: 2020,
    language: "Indonesian",
  },
  {
    title: "Dilan 1991",
    author: "Pidi Baiq",
    genre: "Roman",
    rating: 4.6,
    vibes: ["romantis", "emosional", "menyentuh"],
    themes: ["cinta", "perpisahan", "kenangan"],
    pages: 344,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Milea: Suara dari Dilan",
    author: "Pidi Baiq",
    genre: "Roman",
    rating: 4.5,
    vibes: ["romantis", "reflektif", "emosional"],
    themes: ["cinta", "sudut pandang", "perasaan"],
    pages: 320,
    year: 2021,
    language: "Indonesian",
  },
  {
    title: "Dear Nathan",
    author: "Erisca Febriani",
    genre: "Roman",
    rating: 4.4,
    vibes: ["romantis", "remaja", "manis"],
    themes: ["cinta remaja", "persahabatan", "sekolah"],
    pages: 380,
    year: 2022,
    language: "Indonesian",
  },
  {
    title: "Hujan Bulan Juni",
    author: "Sapardi Djoko Damono",
    genre: "Puisi",
    rating: 4.7,
    vibes: ["puitis", "romantis", "indah"],
    themes: ["cinta", "kerinduan", "keindahan"],
    pages: 120,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Tetralogi Buru - Anak Semua Bangsa",
    author: "Pramoedya Ananta Toer",
    genre: "Fiksi Sejarah",
    rating: 4.7,
    vibes: ["epik", "kuat", "historis"],
    themes: ["kolonialisme", "perjuangan", "identitas"],
    pages: 543,
    year: 2023,
    language: "Indonesian",
  },
  {
    title: "Jejak Langkah",
    author: "Pramoedya Ananta Toer",
    genre: "Fiksi Sejarah",
    rating: 4.6,
    vibes: ["epik", "mendalam", "revolusioner"],
    themes: ["pergerakan", "perjuangan", "nasionalisme"],
    pages: 510,
    year: 2024,
    language: "Indonesian",
  },

  // ========== BUKU INTERNASIONAL POPULER 2020-2025 (50 buku) ==========
  {
    title: "The Midnight Library",
    author: "Matt Haig",
    genre: "Fiction",
    rating: 4.5,
    vibes: ["uplifting", "philosophical", "hopeful"],
    themes: ["choices", "regret", "possibility"],
    pages: 304,
    year: 2020,
    language: "English",
  },
  {
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: "Mystery",
    rating: 4.7,
    vibes: ["atmospheric", "emotional", "lyrical"],
    themes: ["isolation", "nature", "survival"],
    pages: 384,
    year: 2020,
    language: "English",
  },
  {
    title: "The Vanishing Half",
    author: "Brit Bennett",
    genre: "Contemporary Fiction",
    rating: 4.5,
    vibes: ["thought-provoking", "emotional", "layered"],
    themes: ["identity", "race", "family"],
    pages: 343,
    year: 2020,
    language: "English",
  },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    genre: "Fantasy",
    rating: 4.5,
    vibes: ["melancholic", "romantic", "philosophical"],
    themes: ["immortality", "memory", "art"],
    pages: 444,
    year: 2020,
    language: "English",
  },
  {
    title: "Piranesi",
    author: "Susanna Clarke",
    genre: "Fantasy",
    rating: 4.4,
    vibes: ["surreal", "contemplative", "mysterious"],
    themes: ["memory", "solitude", "discovery"],
    pages: 245,
    year: 2020,
    language: "English",
  },
  {
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    genre: "Horror",
    rating: 4.2,
    vibes: ["gothic", "eerie", "atmospheric"],
    themes: ["colonialism", "family secrets", "survival"],
    pages: 301,
    year: 2020,
    language: "English",
  },
  {
    title: "The Guest List",
    author: "Lucy Foley",
    genre: "Thriller",
    rating: 4.3,
    vibes: ["suspenseful", "twisty", "atmospheric"],
    themes: ["secrets", "revenge", "murder"],
    pages: 320,
    year: 2020,
    language: "English",
  },
  {
    title: "Circe",
    author: "Madeline Miller",
    genre: "Fantasy",
    rating: 4.7,
    vibes: ["empowering", "lyrical", "introspective"],
    themes: ["transformation", "power", "isolation"],
    pages: 393,
    year: 2020,
    language: "English",
  },
  {
    title: "Normal People",
    author: "Sally Rooney",
    genre: "Contemporary Fiction",
    rating: 4.3,
    vibes: ["intimate", "realistic", "emotional"],
    themes: ["class", "relationships", "identity"],
    pages: 273,
    year: 2020,
    language: "English",
  },
  {
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    genre: "Fantasy",
    rating: 4.7,
    vibes: ["heartwarming", "whimsical", "cozy"],
    themes: ["acceptance", "family", "love"],
    pages: 394,
    year: 2020,
    language: "English",
  },
  {
    title: "The Four Winds",
    author: "Kristin Hannah",
    genre: "Historical Fiction",
    rating: 4.6,
    vibes: ["heartbreaking", "powerful", "epic"],
    themes: ["survival", "family", "resilience"],
    pages: 454,
    year: 2021,
    language: "English",
  },
  {
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    genre: "Science Fiction",
    rating: 4.3,
    vibes: ["contemplative", "gentle", "philosophical"],
    themes: ["humanity", "love", "technology"],
    pages: 320,
    year: 2021,
    language: "English",
  },
  {
    title: "The Paper Palace",
    author: "Miranda Cowley Heller",
    genre: "Contemporary Fiction",
    rating: 4.1,
    vibes: ["atmospheric", "sensual", "introspective"],
    themes: ["love", "choice", "memory"],
    pages: 384,
    year: 2021,
    language: "English",
  },
  {
    title: "It Ends with Us",
    author: "Colleen Hoover",
    genre: "Romance",
    rating: 4.6,
    vibes: ["emotional", "intense", "heartbreaking"],
    themes: ["love", "abuse", "strength"],
    pages: 384,
    year: 2021,
    language: "English",
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    genre: "Contemporary Fiction",
    rating: 4.6,
    vibes: ["glamorous", "emotional", "compelling"],
    themes: ["identity", "love", "ambition"],
    pages: 388,
    year: 2021,
    language: "English",
  },
  {
    title: "Malibu Rising",
    author: "Taylor Jenkins Reid",
    genre: "Contemporary Fiction",
    rating: 4.4,
    vibes: ["glamorous", "dramatic", "nostalgic"],
    themes: ["family", "fame", "secrets"],
    pages: 369,
    year: 2021,
    language: "English",
  },
  {
    title: "The Last Thing He Told Me",
    author: "Laura Dave",
    genre: "Thriller",
    rating: 4.2,
    vibes: ["suspenseful", "emotional", "gripping"],
    themes: ["family", "secrets", "trust"],
    pages: 320,
    year: 2021,
    language: "English",
  },
  {
    title: "People We Meet on Vacation",
    author: "Emily Henry",
    genre: "Romance",
    rating: 4.5,
    vibes: ["witty", "romantic", "heartwarming"],
    themes: ["friendship", "love", "travel"],
    pages: 364,
    year: 2021,
    language: "English",
  },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Science Fiction",
    rating: 4.7,
    vibes: ["thrilling", "funny", "clever"],
    themes: ["survival", "science", "friendship"],
    pages: 476,
    year: 2021,
    language: "English",
  },
  {
    title: "The Maidens",
    author: "Alex Michaelides",
    genre: "Thriller",
    rating: 4.2,
    vibes: ["dark academia", "suspenseful", "psychological"],
    themes: ["obsession", "grief", "secrets"],
    pages: 336,
    year: 2021,
    language: "English",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    rating: 4.8,
    vibes: ["practical", "motivating", "insightful"],
    themes: ["habits", "productivity", "improvement"],
    pages: 320,
    year: 2022,
    language: "English",
  },
  {
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    genre: "Fiction",
    rating: 4.5,
    vibes: ["nostalgic", "heartfelt", "complex"],
    themes: ["friendship", "creativity", "gaming"],
    pages: 416,
    year: 2022,
    language: "English",
  },
  {
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    genre: "Historical Fiction",
    rating: 4.6,
    vibes: ["witty", "empowering", "charming"],
    themes: ["feminism", "science", "determination"],
    pages: 393,
    year: 2022,
    language: "English",
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Thriller",
    rating: 4.5,
    vibes: ["suspenseful", "twisted", "gripping"],
    themes: ["psychology", "obsession", "secrets"],
    pages: 336,
    year: 2022,
    language: "English",
  },
  {
    title: "Book Lovers",
    author: "Emily Henry",
    genre: "Romance",
    rating: 4.4,
    vibes: ["witty", "charming", "heartwarming"],
    themes: ["love", "books", "family"],
    pages: 368,
    year: 2022,
    language: "English",
  },
  {
    title: "Verity",
    author: "Colleen Hoover",
    genre: "Thriller",
    rating: 4.5,
    vibes: ["dark", "twisted", "suspenseful"],
    themes: ["secrets", "obsession", "manipulation"],
    pages: 336,
    year: 2022,
    language: "English",
  },
  {
    title: "Reminders of Him",
    author: "Colleen Hoover",
    genre: "Romance",
    rating: 4.4,
    vibes: ["emotional", "heartbreaking", "hopeful"],
    themes: ["redemption", "forgiveness", "love"],
    pages: 327,
    year: 2022,
    language: "English",
  },
  {
    title: "The Love Hypothesis",
    author: "Ali Hazelwood",
    genre: "Romance",
    rating: 4.3,
    vibes: ["witty", "steamy", "nerdy"],
    themes: ["fake dating", "academia", "love"],
    pages: 384,
    year: 2022,
    language: "English",
  },
  {
    title: "The Paris Apartment",
    author: "Lucy Foley",
    genre: "Thriller",
    rating: 4.2,
    vibes: ["mysterious", "atmospheric", "suspenseful"],
    themes: ["secrets", "missing person", "Paris"],
    pages: 368,
    year: 2022,
    language: "English",
  },
  {
    title: "The Nightingale",
    author: "Kristin Hannah",
    genre: "Historical Fiction",
    rating: 4.8,
    vibes: ["emotional", "powerful", "heartbreaking"],
    themes: ["war", "sisters", "courage"],
    pages: 440,
    year: 2022,
    language: "English",
  },
  {
    title: "The Song of Achilles",
    author: "Madeline Miller",
    genre: "Historical Fiction",
    rating: 4.8,
    vibes: ["tragic", "poetic", "emotional"],
    themes: ["love", "war", "destiny"],
    pages: 352,
    year: 2023,
    language: "English",
  },
  {
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    genre: "Fantasy",
    rating: 4.7,
    vibes: ["thrilling", "romantic", "action-packed"],
    themes: ["dragons", "war", "power"],
    pages: 498,
    year: 2023,
    language: "English",
  },
  {
    title: "Happy Place",
    author: "Emily Henry",
    genre: "Romance",
    rating: 4.5,
    vibes: ["emotional", "witty", "summery"],
    themes: ["love", "friendship", "growth"],
    pages: 400,
    year: 2023,
    language: "English",
  },
  {
    title: "Holly",
    author: "Stephen King",
    genre: "Horror",
    rating: 4.3,
    vibes: ["creepy", "suspenseful", "dark"],
    themes: ["evil", "courage", "mystery"],
    pages: 464,
    year: 2023,
    language: "English",
  },
  {
    title: "The Heaven & Earth Grocery Store",
    author: "James McBride",
    genre: "Historical Fiction",
    rating: 4.6,
    vibes: ["heartwarming", "powerful", "rich"],
    themes: ["community", "race", "compassion"],
    pages: 384,
    year: 2023,
    language: "English",
  },
  {
    title: "The Wager",
    author: "David Grann",
    genre: "Nonfiction",
    rating: 4.5,
    vibes: ["gripping", "historical", "adventurous"],
    themes: ["shipwreck", "survival", "mutiny"],
    pages: 352,
    year: 2023,
    language: "English",
  },
  {
    title: "Spare",
    author: "Prince Harry",
    genre: "Memoir",
    rating: 4.2,
    vibes: ["revealing", "emotional", "controversial"],
    themes: ["royalty", "family", "identity"],
    pages: 416,
    year: 2023,
    language: "English",
  },
  {
    title: "The Covenant of Water",
    author: "Abraham Verghese",
    genre: "Historical Fiction",
    rating: 4.6,
    vibes: ["epic", "lyrical", "emotional"],
    themes: ["family", "India", "legacy"],
    pages: 736,
    year: 2023,
    language: "English",
  },
  {
    title: "Tom Lake",
    author: "Ann Patchett",
    genre: "Fiction",
    rating: 4.4,
    vibes: ["nostalgic", "intimate", "reflective"],
    themes: ["family", "memory", "theater"],
    pages: 320,
    year: 2023,
    language: "English",
  },
  {
    title: "The Woman in Me",
    author: "Britney Spears",
    genre: "Memoir",
    rating: 4.5,
    vibes: ["revealing", "powerful", "honest"],
    themes: ["fame", "freedom", "resilience"],
    pages: 288,
    year: 2023,
    language: "English",
  },
  {
    title: "Iron Flame",
    author: "Rebecca Yarros",
    genre: "Fantasy",
    rating: 4.8,
    vibes: ["epic", "intense", "romantic"],
    themes: ["war", "betrayal", "dragons"],
    pages: 640,
    year: 2024,
    language: "English",
  },
  {
    title: "The Women",
    author: "Kristin Hannah",
    genre: "Historical Fiction",
    rating: 4.7,
    vibes: ["powerful", "emotional", "important"],
    themes: ["war", "courage", "sacrifice"],
    pages: 480,
    year: 2024,
    language: "English",
  },
  {
    title: "The Housemaid",
    author: "Freida McFadden",
    genre: "Thriller",
    rating: 4.5,
    vibes: ["twisted", "suspenseful", "addictive"],
    themes: ["secrets", "class", "revenge"],
    pages: 336,
    year: 2024,
    language: "English",
  },
  {
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    genre: "Fantasy",
    rating: 4.7,
    vibes: ["romantic", "magical", "thrilling"],
    themes: ["love", "sacrifice", "magic"],
    pages: 419,
    year: 2024,
    language: "English",
  },
  {
    title: "The Vaster Wilds",
    author: "Lauren Groff",
    genre: "Historical Fiction",
    rating: 4.3,
    vibes: ["atmospheric", "intense", "primal"],
    themes: ["survival", "nature", "freedom"],
    pages: 272,
    year: 2024,
    language: "English",
  },
  {
    title: "The Familiar",
    author: "Leigh Bardugo",
    genre: "Fantasy",
    rating: 4.4,
    vibes: ["dark", "magical", "historical"],
    themes: ["magic", "power", "Spain"],
    pages: 464,
    year: 2024,
    language: "English",
  },
  {
    title: "All Fours",
    author: "Miranda July",
    genre: "Fiction",
    rating: 4.2,
    vibes: ["quirky", "provocative", "experimental"],
    themes: ["identity", "desire", "midlife"],
    pages: 320,
    year: 2024,
    language: "English",
  },
  {
    title: "The God of the Woods",
    author: "Liz Moore",
    genre: "Mystery",
    rating: 4.5,
    vibes: ["atmospheric", "mysterious", "layered"],
    themes: ["family secrets", "wilderness", "truth"],
    pages: 480,
    year: 2025,
    language: "English",
  },
  {
    title: "Just for the Summer",
    author: "Abby Jimenez",
    genre: "Romance",
    rating: 4.6,
    vibes: ["heartwarming", "witty", "emotional"],
    themes: ["love", "family", "healing"],
    pages: 384,
    year: 2025,
    language: "English",
  },
  {
    title: "Funny Story",
    author: "Emily Henry",
    genre: "Romance",
    rating: 4.5,
    vibes: ["witty", "romantic", "fun"],
    themes: ["love", "friendship", "healing"],
    pages: 400,
    year: 2025,
    language: "English",
  },
]

async function main() {
  console.log('🌱 Starting seed process for PaperPulse...')
  
  // Delete existing books first
  await prisma.book.deleteMany({})
  console.log('🗑️  Cleared existing books')
  
  let createdCount = 0
  
  for (const book of sampleBooks) {
    await prisma.book.create({
      data: book,
    })
    createdCount++
  }
  
  console.log('✅ Seeding finished successfully!')
  console.log(`📚 Total books created: ${createdCount}`)
  console.log(`🇮🇩 Indonesian books: ${sampleBooks.filter(b => b.language === 'Indonesian').length}`)
  console.log(`🌍 International books: ${sampleBooks.filter(b => b.language === 'English').length}`)
  console.log(`📅 Year range: 2020-2025`)
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
